nuxt-modules/storybook

- docs/content/en/manual-setup.md
- examples/manual-setup/storybook/preview.js
- storybook/preview.js
> fix: allow using custom `srcDir`

- examples/manual-setup/package.json
- examples/mdx/package.json
- examples/tailwind/package.json
Very awesome 💯 🤩 
I just wanted to see the examples on codesandbox, but codesandbox does not run  the scripts with `storybook`.
https://codesandbox.io/docs/environment#container-environment
> chore(examples): add server scripts for codesandbox

- .eslintignore
- docs/content/en/commands.md
- docs/content/en/manual-setup.md
- src/cli.ts
- src/index.ts
- src/types.d.ts
- src/utils.ts
- storybook/eject/main.js
- storybook/eject/preview.js
> feat(cli): introduce `eject` command

- docs/content/en/commands.md
- docs/content/en/examples.md
- docs/content/en/index.md
- docs/content/en/manual-setup.md
- docs/content/en/options.md
- docs/content/en/setup.md
- docs/content/en/usage.md
Remove outdated `categoryPosition` attribute from front-matter
> docs: remove useless category position

- docs/content/en/commands.md
- src/cli.ts
- src/index.ts
- src/types.d.ts
Introduce `--config-file` flag
close #55
> feat(cli): support nuxt's custom config file

- examples/mdx/components/AwesomeButton.stories.js
- examples/mdx/components/AwesomeButtonX.stories.mdx
- examples/mdx/nuxt.config.js
- examples/mdx/package.json
- package.json
- playground/nuxt.config.js
- src/preset.ts
- yarn.lock
Support Storybook v6
close #39
> feat(storybook): Migration to Storybook v6

- .eslintignore
- src/index.ts
- src/webpack.ts
- storybook/entry.js
- storybook/preview.js
> feat(storybook): custom Vue app based on nuxt `createApp`

- package.json
- playground/stories/env.stories.js
- src/webpack.ts
add DefinePlugin to valid plugins to integrage Storybook environment variables
close #90
> feat(storybbok): Integrate Storybook environment variables

- playground/nuxt.config.js
- playground/stories/publicRuntimeConfig.stories.js
- storybook/entry.js
Add support for Nuxt [runtime config](https://nuxtjs.org/guide/runtime-config)
close #87
> feat(storybook): support nuxt runtime config

- docs/content/en/options.md
- package.json
- storybook/main.js
Support addon configurations on storybook config
close #100
> feat(storybook): support addon config

- docs/content/en/options.md
- package.json
- playground/nuxt.config.js
- src/index.ts
- storybook/preview.js
- yarn.lock
Support Storybook's global [parameters](https://storybook.js.org/docs/react/writing-stories/parameters) in `nuxt.config` 
close #110
> feat(storybook): add global parameters in nuxt config

- docs/content/en/options.md
- package.json
- src/index.ts
- src/preset.ts
- yarn.lock
Essential addons widely used in the storybook world, after #84 I found it more convincing that integrate this addons inside the module.
close #84
> fea(storybook): integrate essential addons

- src/index.ts
The parallel build will break the storybook.
Close #102
> fix(webpack): Storybook do not work with thread-loader

- storybook/nuxt-entry.js
> fix(storybook): prevent scripts conflict in nuxt-entry

- docs/content/en/manual-setup.md
The word official is missing the letter f on the English manual setup description. This PR adds the missing letter.
> docs: Fix typo

- src/cli.ts
- src/index.ts
- src/types.d.ts
Nuxt always runs commands using `node` therefore running `nuxt-ts storybook` does not work as expected.  With this PR `@nuxtjs/storybook` will check `tscofnig.json` and register `ts-node` when it's required.
close #160
> feat: support typescript runtime

- storybook/eject/preview.js
In the ejected mode (manual setup) global parameters does not exports in `preview.js`. Without export Storybook cannot detect paramteres.  
close #168
> fix: export global parameters on eject mode

- docs/content/en/options.md
- src/index.ts
- storybook/preview.js
Add support for global decorators.
close #120
> feat: decorators option

- src/index.ts
Listen to `watch:restart` hook and rebuild Nuxt on changes. Nuxt does the same on dev [here](https://github.com/nuxt/nuxt.js/blob/3c4f9e4574208dd75f3115d89ce6ec7988d39d74/packages/cli/src/commands/dev.js#L53)
> feat: rebuild nuxt on file change 

- src/index.ts
Fix source map issue with third-party stories that provided by modules. 
close #208
> fix: prevent source map error on external stories

- .github/workflows/ci.yml
- CHANGELOG.md
- docs/content/en/manual-setup.md
- package.json
- src/index.ts
- yarn.lock
- `storybook`
- prevent Webpack source map error (#212)
- update manual setup docs
- update storybook v6.1.14
> docs: update manual setup

- playground/nuxt.config.js
- src/index.ts
- storybook/preview.js
> feat(module): globalTypes in Nuxt config

- docs/content/en/usage.md
Mentions that the usage examples require the `components: true` option to be set in `nuxt.config`.
Resolves #234
> docs: mention components:true in usage examples

- .eslintignore
- README.md
- playground/components/GithubUsers.vue
- playground/nuxt.config.js
- src/index.ts
- storybook/middleware.js
Adds middleware that uses the @nuxtjs/proxy module and it's configuration to provide proxy functionality within Storybook.
> feat: support for @nuxtjs/proxy module

- storybook/main.js
Fix `ReferenceError: path is not defined` error while start
> fix: add missed path dependency in main.js

- package.json
- yarn.lock
Freeze Storybook to prevent 6.2+ to break users remaining on version 3.
Resolves: #252
> fix(deps): freeze storybook

- docs/content/en/API.md
> docs: typo

- docs/package.json
- docs/yarn.lock
Currently, Document is broken by `@nuxt/content-theme-docs@0.10.2.`
In the near future, `@nuxt/content-theme-docs` will be deprecated and will be replaced by `docus`.
However, since `docus` has not been released yet, we will revert `@nuxt/content-theme-docs` to `0.10.1`, which is not broken, as a temporary measure.
|before|after|
|-|-|
|![image](https://user-images.githubusercontent.com/49480575/120653673-e2ec5680-c4bb-11eb-9258-8e3371393b40.png)|![image](https://user-images.githubusercontent.com/49480575/120653756-f7305380-c4bb-11eb-9495-52761840b42d.png)|
- [Pending docus PR](https://github.com/nuxt-community/storybook/pull/216)
- [Similar PR](https://github.com/nuxt-community/snipcart-module/pull/27)
- https://github.com/nuxt/content/issues/863
- …
> docs: fix broken docs

- storybook/middleware.js
> fix: support functions as middleware

- playground/nuxt.config.js
- playground/plugins/nop.server.js
- src/index.ts
> fix: filter server plugins

- package.json
- src/webpack.ts
- yarn.lock
- Updated Storybook to 6.4
- Updated webpack entry point replace regex
- Resolves #354
> feat(#354): update storybook to 6.4

- .gitpod.yml
- README.md
- adds a `.gitpod.yml` file that:
- installs node v15 via nvm
- installs dependencies
- builds codebase
- runs dev
- adds eslint, editorconfig and vetur
- exposes port 3003
> docs: add Gitpod configuration

- README.md
> chore: add docs link storybook-vue/nuxt

- README.md
i added instruction to how use Nuxt 2
> add Nuxt 2 support instruction

- package.json
i changed module package name to @nuxtjs/storybook-legacy for Nuxt 2 support
> Update package.json rename to @nuxtjs/storybook-legacy

- docs/content/2.storybook/1.config.md
Code is typescript; set filename to typescript
> doc: typescript consistently

- docs/content/2.storybook/1.config.md
Update storybook configuration url
> Update 1.config.md - storybook configuration url

- src/module.ts
related #486 .
When the Storybook version was updated in this PR ( #486 ), JSDoc comment update was omitted.
This has been corrected to avoid confusion for future committers.
> chore: fix Storybook version of comment

- src/module.ts
Hi :wave: 
this fix #510
This PR remove the line which disable SSR.
> fix: remove disable ssr

- .github/workflows/ci.yml
- package.json
- pnpm-lock.yaml
- src/module.ts
A few smaller ci improvements:
- Add build command (and a few that are currently failing)
- Update version of actions
- Move pnpm version to package.json
- Fix build error and a few build warnings
> chore: improve ci workflow

- .github/workflows/ci.yml
- docs/package.json
- playground/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Now the playground should build
> chore: migrate to pnpm workspace to fix playground

- docs/content/2.storybook/1.config.md
> docs: replace tailwind by storybook in docs

- packages/storybook-nuxt/src/preset.ts
Exit the nuxt build after we get the vite config, which is all we care for.
> feat: improve build performance by no longer building the whole nuxt application for storybook

- package.json
- pnpm-lock.yaml
- src/module.ts
Introduced in https://github.com/nuxt/nuxt/pull/27022.
> feat: declare module incompatibility for webpack

- packages/storybook-addon/src/preset.ts
- packages/storybook-addon/src/preview.ts
- packages/storybook-addon/src/runtimeConfig.ts
- playground/.storybook/main.ts
Fixes https://github.com/nuxt-modules/storybook/issues/662.
> fix: correctly provide Nuxt runtime config in storybook

- docs/nuxt.config.ts
- package.json
- test/docs.test.ts
Using workaround for https://github.com/nuxt/content/issues/2688. Also add tests that hopefully catch such issues in the future.
Fixes https://github.com/nuxt-modules/storybook/issues/680
> chore: fix deployment of docs

- prepare-release.ts
Add tag creation in prepare-release script
> chore: add tag creation in prepare-release script

- CHANGELOG.md
- packages/nuxt-module/package.json
- packages/storybook-addon/package.json
- packages/storybook-addon/src/preview.ts
> bugfix:ts-error __NUXT__

- package.json
- packages/storybook-addon/src/preview.ts
This PR fixes prettier errors that cause the CI to fail, and adds a `lint:fix` script to fix the errors locally.
> chore: fix prettier errors

- renovate.json5
> chore: update renovate config to not ignore 'examples' directories

- packages/storybook-addon/src/preset.ts
> fix: update Vite configs to include lodash/kebabCase in optimizeDeps

- packages/storybook-addon/src/preset.ts
> fix: resolve module not found error '@storybook/builder-vite'

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- package.json
- packages/nuxt-module/package.json
Add tests verifying that installing storybook in a nuxt starter app is working fine.
> chore: add e2e tests

- packages/storybook-addon/src/preview.ts
> chore: fix typescript error

- .github/workflows/ci.yml
> chore: try to fix nightly release

- .github/workflows/ci.yml
> chore: try to publish nightly versions for all packages

- packages/nuxt-module/src/storybook.ts
To fix warning when starting storybook.
> fix: update storybook version to 8.2.7

- .github/workflows/ci.yml
- package.json
- pnpm-lock.yaml
- prepare-release.ts
To fix the release of the nightly version.
> chore: increase version before publishing nightly

- docs/content/1.getting-started/1.setup.md
> docs: Add instructions for opting in and out of nightly builds

- docs/content/1.getting-started/1.setup.md
> docs: nightly release dependency package name

- package.json
- pnpm-lock.yaml
> chore: remove unused jsdom dev dependency

- .github/FUNDING.yml
@chakAs3 Feel free to add other funding information if applicable.
> chore: Add GitHub funding information

- renovate.json5
Pin all @storybook/* packages because even minor updates can break things for us.
> chore: pin @storybook/* packages

- packages/storybook-addon/src/preview.ts
https://github.com/nuxt/ecosystem-ci/actions/runs/10992395313/job/30518000761
The type of `$fetch.create` and the global `$fetch` object exposed by nitro differ. (The latter is strongly typed based on your api routes.)
> fix: suppress fetch type warning

- .github/workflows/ci.yml
- package.json
to avoid any confusion with prerelease, when runing pnpm release, i faced a weird issue while releasing
> chore(ci): update CI workflow to use nightly-release change the script name

- packages/nuxt-module/package.json
- packages/storybook-addon/package.json
- playground/package.json
- pnpm-lock.yaml
> Pin storybook packages

- .github/workflows/e2e.yml
> chore: fix starter examples

- docs/content/1.getting-started/1.setup.md
> Not based on an issue.
This PR updates the code example at the bottom of the [Setup page](https://storybook.nuxtjs.org/getting-started/setup) so that it mirrors the code example on the next page [Options](https://storybook.nuxtjs.org/getting-started/options).
> docs: replace url property with host

- packages/storybook-addon/package.json
- packages/storybook-addon/src/preset.ts
- pnpm-lock.yaml
> chore: upgrade json-stable-stringify and remove obsolete `@types` package

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
Node 18/19 support will be dropped anyway in Storybook v9, so there is little point in still testing it.
> chore: update tested Node versions in ci

- examples/showcase/components/MyI18n.vue
- examples/showcase/package.json
- playground/package.json
- playground/stories/MyI18n.vue
- pnpm-lock.yaml
* #899 
Resolves #899 
Updates nuxt-i18n to a compatible version and updates the i18n components in playground and showcase to use types and functions as recommended by the docs.
#899 is actually resolved by https://github.com/nuxt-modules/i18n/pull/3690, though instances will still get mixed up across stories (unrelated to nuxt-i18n).
> fix: update `@nuxtjs/i18n`

- pnpm-lock.yaml
Hopefully fixes the documentation build.
> chore: dedupe dependencies

- netlify.toml
> chore: update Node.js version to 22.17.1 in Netlify configuration

- docs/package.json
- pnpm-lock.yaml
To hopefully fix:
```
[error] Module did not self-register: '/opt/build/repo/node_modules/.pnpm/better-sqlite3@11.9.1/node_modules/better-sqlite3/build/Release/better_sqlite3.node'.
1:16:00 AM:   at Object..node (node:internal/modules/cjs/loader:1921:18)
1:16:00 AM:   at Module.load (node:internal/modules/cjs/loader:1465:32)
1:16:00 AM:   at Function._load (node:internal/modules/cjs/loader:1282:12)
1:16:00 AM:   at TracingChannel.traceSync (node:diagnostics_channel:322:14)
1:16:00 AM:   at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
1:16:00 AM:   at Module.require (node:internal/modules/cjs/loader:1487:12)
1:16:00 AM:   at require (node:internal/modules/helpers:135:16)
1:16:00 AM:   at bindings (/opt/build/repo/node_modules/.pnpm/bindings@1.5.0/node_modules/bindings/bindings.j …
```
> chore: add better-sqlite3 as dependency for docs

- .github/workflows/e2e.yml
> chore: disable testing on Node 21 due to known issues
