src/cli.ts

Make sure NODE_ENV is `development`.
**NOTE:** While using `nuxt` to execute commands, Nuxt set NODE_END to `production` if it is missing.
see: https://github.com/nuxt/nuxt.js/blob/dev/packages/cli/src/setup.js#L9
Fix #38

fix(cli): run storybook in `development` env

---

docs/content/en/commands.md
src/cli.ts
src/index.ts
src/types.d.ts

Support [Storybook flags](https://storybook.js.org/docs/configurations/cli-options/) in cli.  
Supported flags:
- `--output-dir`
- `--quiet` 
- `--static-dir`
- `--port` 
- `--host` 
- `--ci` 
- `--smoke-test`
fix #37

feat(cli): support storybook flags

---

src/index.ts

Support multiple static directories and ensure `staticDir` is always an array
close #65

feat(storybook): support multiple staticDir

---

storybook/index.js
storybook/preview.js

Made sure that backslashes from win32 paths (still on that mighty quest) are escaped "twice" when interpolated through Lodash templates, not familiar with Lodash's templates so I'm not sure if this is the most effective way to do that (although it's apparently the same one which is used in [nuxt/utils](https://github.com/nuxt/nuxt.js/blob/1edac29eba1a621339105f5adef73d4c30388fee/packages/utils/src/resolve.js#L15)), feel free to correct me, but it's working still ^^'
Currently `@nuxtjs/storybook` does not work on platform using win32 paths (aKa Windows) because when `styles` array gets interpolated, win32 paths, after they got resolved (i.e. the `~/assets/css/tailwind.css` coming from `@nuxtjs/tailwindcss` module), needs to be escaped twice.
<details>
<summary>Current output at …

fix(storybook): escape win32 paths

---

examples/manual-setup/storybook/main.js
src/index.ts
src/preset.ts
storybook/main.js

Starting v6, Storybook changes glob behavior and shows a warning when it can't find a story.
This happens because we use Nuxt aliases in the glob patterns.
close #75

fix(storybook): resolve nuxt aliases in globs

---

package.json
src/index.ts
yarn.lock

Added [upath](https://www.npmjs.com/package/upath) to normalize paths to POSIX specs (same strategy as here https://github.com/nuxt/nuxt.js/pull/7796) and used it when resolving glob patterns for `stories` array.
With `2.1.0`, generated `.nuxt-storybook/storybook/main.js` looks like this on Windows:
```javascript
module.exports = {
webpackFinal(config, options) {
return options.nuxtStorybookConfig.webpackFinal(config, options)
},
stories: ['..\../components/**/*.stories.@(ts|js)'],
}
```
The above is not a valid [glob pattern](https://www.npmjs.com/package/glob#glob-primer) and will lead to a fatal error while running Storybook. Since glob patterns are expected to use the POSIX separator this use upath to normalize them and will fix globs array:
```javascript
module.exports = { …
```

fix(storybook): normalize win32 paths for storybook globs

---

src/index.ts

Static dirs are relative to srcDir of nuxt, Currently they are treats as rootDir relatives
close #106

fix(storybook): resolve static dir relative to src dir

---

src/index.ts

Ensure `components/` folder exists before pushing default stories path.
The `~/components/**/*.stories.@(ts|js)` path is forced and an error is thrown when missing. 
I'm using `@nuxtjs/storybook` to create docs for a nuxt module and I don't have a `components/` folder. In my `docs/` folder I just have a `nuxt.config.js`:
```js
import { join } from 'path'
import module from '..'
export default {
components: true,
buildModules: [module],
storybook: {
stories: [join(__dirname, '../lib/components/**/**.stories.js')]
}
}
```

fix(storybook): ensure default `components/` dir exists

---

storybook/mock/nuxt-link.js

Adjusted the Proptype for the nuxt-link mock
Nuxt Storybook gives errors in console.log when you pass an Object to the to prop (which is allowed and common ). 
No tests as it's a very minor change and none of the existing test cases cover it.

fix(storybook): Allow nuxt-link mock to take an Object for the to prop

---

README.md

During #23 the .nuxtignore entry was added in 670ea295f09aeede3decbc1552cf6e2e6bc0fbce but later removed from setup.md in 557c56b9c13df34e246668db6a4bf1b60b8116d8 (PR #96) after the nuxt/components has implemented this directly.
Keeping this in README was probably just an oversight as seen by the issue development. I randomly noticed this discrepancy by searching if there's any mention about this .nuxtignore entry and what are its consequences, as it seemed to be quite a project bloating with zero configuration.

docs: update README (remove .nuxtignore)

---

src/index.ts
src/preset.ts
src/webpack.ts

Because storybook run presets before `main.js`, the aliases are not available in addons.
close #152

fix(module): move aliases to preset

---

storybook/nuxt-entry.js

Suddenly stories are rendered twice and in the first render, they are not a descendent of the Nuxt app. 
This PR changes the render function to return `null` if the story wants to render outside of the Nuxt context. 
close #190 #193

fix: prevent rendering outside of nuxt context

---

package.json
playground/nuxt.config.js
storybook/nuxt-entry.js
yarn.lock

Import plugins after plugin scripts. 
Originally reported in: https://github.com/nuxt-community/color-mode-module/issues/69

fix(plugins): execute plugin scripts before imports

---

.github/workflows/ci.yml
examples/manual-setup/package.json

The `nuxt-storybook build` in a project fails under Windows, so to illustrate the issue, I've added a GitHub Actions CI test coverage to show a reproducible example. Other than pointing out the issue, I'd also suggest for you to explicitly add (all the) other examples to some test, because at the moment they aren't covered at all, which causes false expectations of the latest release being stable. Please iterate upon this commit before merging, as I only covered one example (and without CI caching).
The `nuxt-storybook build` doesn't seem to work under Windows, as it fails with the following error:
```
info => Cleaning outputDir D:\a\storybook\storybook\examples\manual-setup\storybook-static
ERR! Error: no such directory to load static files: …
```

test: enable windows runner

---

src/index.ts

As it turns out some server plugins are still copied over to the .nuxt-storybook folder after #290 was merged. The regex doesn't match all filenames.
Some server plugins are not copied over to the .nuxt-storybook folder after #290 was merged. The regex doesn't match all filenames. I encountered files names such as: `/Users/timbenniks/Websites/timbenniks-vnext/.nuxt-storybook/lib.intent-manifest-fetcher-plugin.server.99303334.js`
The regex in #290 expects `server.js`. I have added a more flexible pattern: `\.server\.?(.*)\.(ts|js)`.

fix: Make sure to ignore all Nuxt server plugins

---

storybook/middleware.js

In the context of building storybook in bridge, I got an empty server middleware object for some reason (not sure why). This then lead to `_handler` being undefined and thus `app.use` throws an error.
As a quick fix, I've added an if check to test if `_handler` is defined before calling `app.use`.

fix: missing handler in server middleware

---

src/index.ts
storybook/package-template.json

If you have `type: module` in your main `package.json`, then storybook doesn't work. This is not an issue with the nuxt module, but with upstream storybook, see https://github.com/storybookjs/storybook/issues/11587. 
In this issue, a workaround is outlined which involves creating a `package.json` in the `storybook` folder.
This is added with this PR.

fix: create dummy package.json for ESM compatibility

---

docs/content/1.getting-started/1.installation.md

Remove postcss as a getting started requirement
Remove unneeded postcss dependency to be installed to get started as documented on the getting started docs page

docs: remove `postcss` from install script

---

docs/content/1.getting-started/3.commands.md
src/cli.ts
src/types.d.ts

Adds support for the `--webpack-stats-json` flag so Chromatic can pass it through successfully and Nuxt Storybook can be used to publish to Chromatic with TurboSnap enabled.
[Chromatic](https://www.chromatic.com/), a cloud-based tool used to publish Storybook instances and facilitate UI review, has a feature called [TurboSnap](https://www.chromatic.com/docs/turbosnap) which allows smart snapshotting for visual regression testing.  When publishing Storybook using the Chromatic CLI and the `--only-changed` flag to activate TurboSnap, it calls `build-storybook` and attempts to pass the `--webpack-stats-json` flag automatically, which causes the command to fail and prevents using TurboSnap with Nuxt Storybook.

feat(cli): Support chromatic's `--webpack-stats-json` flag

---

storybook/nuxt-entry.js

Since version 4.3.0, args/controls don't work (#373). That's because the argument passed to the render function does not have any `args` object passed to it (it's always undefined). The `args` are now available in the `storyContext` object that is passed to the render function.
This is already used in storybook's [latest vue render function](https://github.com/storybookjs/storybook/blob/7ffc089ca285da0f2e7a68af4d36592e149f715d/app/vue/src/client/preview/render.ts#L63)

fix: `undefined` render args argument

---

src/cli.ts

Don't override the `NODE_ENV` if it's already set.
When runnnig storybook, I need to use special setting in my `nuxt.config.js`. I tried to set `NODE_ENV` to any value (`storybook` for example), but the module would always override it.
I think this should be the default behavior and would not require test or documentation.

fix: keep `NODE_ENV` set by users

---

src/index.ts

Resolves #359. With bridge, we need some compatibility plugins to run in order to support new API such as `useNuxtApp()`. These plugins are currently being filtered because their mode is (newly unhandled) `all`. This PR avoid filtering them out.

fix: include plugins with `mode: 'all'`

---

src/index.ts

This is essentially a backport of https://github.com/nuxt-modules/storybook/pull/405.
We need this fix to use Nuxt/Bridge

(v4) include plugins with mode: 'all' for bridge compatibility

---

package.json
pnpm-lock.yaml

Currently one has to install `@storybook-vue/nuxt` manually. Moreover, during the first run of `nuxi dev` storybook is downloaded, leading to an unpredictable version (e.g. currently it is v8). Both of these issues are fixed by declaring both `@storybook-vue/nuxt` and `storybook` as dependencies of this module. This is in line with other modules that also declare all dependencies. (It would make sense perhaps to declare storybook as a peer dependency.)
Fixes #476.

fix: add storybook as dependency

---

README.md
docs/content/0.index.md
docs/content/1.getting-started/1.setup.md

This updates the documentation to use the [`nuxi module add` command](https://github.com/nuxt/cli/pull/197) which should simplify docs a bit and also improve user experience as there's no need to add to `nuxt.config` manually.
It's documented [here](https://nuxt.com/docs/api/commands/module#nuxi-module-add).
I may have missed a few spots in the documentation as I'm doing this across the modules ecosystem assisted by the power of regular expressions ✨, so I'd appreciate a review 🙏

docs: use new `nuxi module add` command in installation

---

src/storybook.ts

Removes setting the `devtools` option, as users of the module can decide that on their own.

fix: do not change nuxt devtools config

---

src/module.ts
src/storybook.ts

- Remove some of the unused module options
- Change the behavior of the route to default to `_storybook` as described in the docs
- Rename some of the options (the `storybook` prefix  is unnecessary in my opinion). This is a breaking change, although I doubt many users used these options (the `storybookUrl` option was not even working)

fix!: improve handling of module options

---

src/module.ts
src/storybook.ts

Close: https://github.com/nuxt-modules/storybook/issues/538

fix: fix TypeError when reading '__STORYBOOK__' property of undefined

---

.github/workflows/ci.yml

Currently fails with "There are no new packages that should be published". Since we don't update the version before publishing to the `next` tag, we use the `--force` argument to overwrite the version check. This hopefully fixes the publishing of the nightly release.

chore: fix publishing of nightly releases

---

README.md

The README states that this module supports Storybook version 7, while the actually-supported version is 8.
Some other typos in the README were also fixed.

docs: clarify supported Storybook version

---

.npmrc
pnpm-lock.yaml

Now pnpm no longer removes the `link` from the package lock file.

chore: fix linking of workspace packages

---

examples/showcase/components/globalComp.global.vue
examples/showcase/components/globalComp.stories.ts
packages/storybook-nuxt/src/preset.ts

`@vitejs/plugin-vue` should be the first registered user plugin so that it will be added directly after Vite's core plugins and transforms global vue compoments before nuxt:components:imports. The transform stack order can be reviewed with the `vite-plugin-inspect` plugin.
This fixes the use of global components in projects or modules.
Fixes https://github.com/storybook-vue/storybook-nuxt/issues/4.

fix: fix order of vite vue plugin

---

packages/storybook-nuxt/src/preset.ts

Similar to https://github.com/nuxt/test-utils/blob/66b23ae6f3d717690551ff1908647ff0f0cfa63b/src/config.ts#L37-L38

fix: use appId and buildId as fallbacks, use `vite:configResolved` hook 

---

packages/storybook-addon/src/preset.ts

Fixes the issue mentioned in https://github.com/nuxt-modules/storybook/issues/658#issuecomment-2191492289

fix: update file extensions for generated vite configs to use .json instead of .js

---

renovate.json5

Following https://docs.renovatebot.com/dependency-pinning/ since we have a bit of problems with handling the dependencies currently. In particular, https://github.com/nuxt-modules/storybook/pull/690 updates a package (in the lock file) that is not working, and its not easy to just revert that particular update.

chore: tell renovate to pin all development and doc dependencies

---

packages/storybook-addon/build.config.ts

Maybe fixes the errors reported at https://github.com/nuxt-modules/storybook/issues/670#issuecomment-2222388747.

chore: mark a few more imports as external to fix build warnings

---

package.json
packages/storybook-addon/src/runtime/components/nuxt-link.ts
pnpm-lock.yaml

The Renovate PR #706 is failing the CI because newer version of Prettier now requires brackets around a return in `nuxt-link` component. This PR updates Prettier and fixes the `nuxt-link` prettier problem

chore(deps): update prettier and lint

---

packages/nuxt-module/src/storybook.ts

Fixes https://github.com/nuxt-modules/storybook/issues/704
Instead of actually loading the package json, we just pass a javascript object with a `version` field. That is the only thing used by storybook. It's a temporary workaround until https://github.com/storybookjs/storybook/pull/28594 is merged.

fix: fix error due to import json attribute (and deactivate storybook version check)

---

playground/package.json
pnpm-lock.yaml

Devtools were not working in playground due to old devtools dependency, which is no longer needed.

chore: fix devtools in playground

---

packages/storybook-addon/src/preview.ts

Related #661
This PR updates the global nuxt context, setting its `nuxt` property to the story's nuxt when setting up the current story.
Previously, when navigating from one story to another story, Nuxt would get the context using the app's `_name`, which is the same for all stories, instead of using the `globalName`, which is different for each story.

fix: remove Nuxt context conflict

---

packages/storybook-addon/package.json
packages/storybook-addon/src/preview.ts
pnpm-lock.yaml

This finally fixes #661.
With https://github.com/nuxt/nuxt/pull/28392 it is now possible to key the context to the correct nuxt instance.
Breaking change since we need the newest nuxt version for this to work.

fix!: properly handle context when using multiple nuxt instances

---

docs/content/1.getting-started/2.options.md
packages/nuxt-module/src/module.ts
packages/nuxt-module/src/storybook.ts

With this module it's easy to set-up a storybook env. but it isn't possible to use a ssl certificate like the CLI does: 
`storybook dev -p 6006 --https --ssl-cert ./secrets/cert.pem --ssl-key ./secrets/key.pem`.
To make that possible with this module I've added/exposed the https options. I used the same format as Nuxt [devServer.https](https://nuxt.com/docs/api/nuxt-config#https) options.  
You could even argue that we could just reuse the https options from the devServer section directly if they're defined. But to keep it flexible I've kept them separate. 
- Generate a SSL key & cert with e.g. https://github.com/Subash/mkcert
- Add those to the playground folder
- Add in the nuxt.config.ts of the playground with the right paths:
```
storybook: {
https: {
key: './key.pem',
cert: …
```

feat: Exposing the https options for Storybook dev server

---

packages/nuxt-module/src/storybook.ts

The Storybook versions in the `package.json` were updated, but the same change needs to be added to the `storybook.ts` to prevent version conflicts.
Currently, with nightly, we get the following error:
```
WARN The following packages are incompatible with Storybook 8.2.7 as they depend on different major versions of Storybook packages:
WARN - @nuxtjs/storybook@8.3.0-28764731.a9bf66d
WARN  Repo: https://storybook.nuxtjs.org
WARN - @storybook-vue/nuxt@8.3.0-28764731.a9bf66d
WARN  Repo: https://storybook.nuxtjs.org
WARN - storybook@8.2.9
WARN  Repo: https://github.com/storybookjs/storybook/tree/next/code/lib/cli
WARN - @storybook/vue3@8.2.9
WARN  Repo: https://github.com/storybookjs/storybook/tree/next/code/renderers/vue3
WARN - @storybook/addon-links@8.2.9
WARN  Repo: …
```

fix: remove Storybook version from `storybook.ts`

---

docs/content/1.getting-started/1.setup.md

Resolves #793
Actually module will not automatically generate a basic configuration and you have to create
`.storybook/main.{ts,js}`
`.storybook/preview.{js,cjs,mjs,ts}`

docs: module will not automatically generate a basic configuration

---

packages/nuxt-module/README.md

added Readme  was missing on the nuxt module package

Add README to nuxt module package

---

packages/storybook-addon/src/preset.ts

This PR extends the preset for the server proxy, to also allow the fetching of NuxtIsland components from the dev server.
Standalone stories for NuxtIslands work fine. But when you have a component that has a NuxtIsland component in it, it won't render (properly) because it can't find the server only parts in the Storybook server. With this PR those routes are exposed and make the stories render.
There's one thing left to make NuxtIsland's work without any user changes needed: a Suspense wrapper, but I wasn't too sure if/where that should be enabled by default. 
https://github.com/nuxt-modules/storybook/compare/main...brandondv:nuxtjs-storybook:feature/child-nuxt-island-stories

Fix: Extend the server proxy preset to also fetch SSG NuxtIslands

---

packages/storybook-addon/src/preset.ts
playground/package.json
pnpm-lock.yaml

Fixes https://github.com/nuxt-modules/storybook/issues/808 and fixes https://github.com/nuxt-modules/storybook/issues/805.
This PR reverts #740  that removes of the vue-templation-template plugin, which was initially extended from the vue3-vite project vite config. However, removing it only masked the memory issue rather than addressing its root cause—the resolution of the vue ESM bundler alias.
The vue-templation-template plugin is essential for rendering stories with custom string templates, so we need to retain it.
To work around the memory issue and ensure template compilation works correctly, i have added vue as a dependency in the root project. ( playground )
The underlying problem appears to be related to how the vue alias is resolved. When it isn’t found in the root project, some …

fix: readd vue-tempate-compilation plugin

---

.github/workflows/ci-examples.yml

Currently the workflow passes even though there are changes in the examples. Thus, one always have to manually check the chromatic app before merging a PR, which gets tiresome.
Refs https://github.com/nuxt-modules/storybook/issues/710

chore: fail workflow if chromatic finds changes in examples

---

docs/content/1.getting-started/1.setup.md

This PR adds a warning note to inform users about the differences between running `storybook` with `nuxt` or on its own.

docs: add warning about differences between running `storybook` with `nuxt` or on its own

---

packages/nuxt-module/package.json
packages/storybook-addon/package.json
renovate.json5

Resolves #907
This PR fixes peerDependency storyblock dependency to use a semver range. In #882 storybook was implemented as a peer dependency to the 2 packages of this repo, and was given a range of `^9.0.4`. But then in #905 the Renovate bot updated storybook to `9.0.5`, including the peer dependency of it, and pinned the version to `9.0.5`, leading to #907
This PR fixes that
NB: Make sure that the new rule I've implemented in the Renovate config matches the group settings you want

fix: 🐞 Fix semver range update in Renovate in peerDependencies breaking peer dependency compatability

---

packages/nuxt-module/src/storybook.ts

* #920 
With https://github.com/nuxt/nuxt/pull/32601 merged, the related issue will be resolved for projects using nuxt 4.
This will also improve/add support for the directory structure in nuxt 4 as the `.storybook` directory is outside the app/server directories and needs to be added manually by this module.
~~If we also want this resolved for projects using nuxt 3, the PR will either need to be backported (ideal) or we could use my package nuxt-module-utils (I have not done so in this PR, I don't want to be pushy with my own packages 😂).~~
(this is not relevant since the separated tsconfig structure is nuxt 4 only)

fix: include config dir in tsconfig

---

package.json
prepare-release.ts

This PR adds a simple way to manually trigger major version bumps when needed, particularly useful for ecosystem alignment (e.g., when Storybook releases a new major version).
- **Added `release:major` script** to `package.json` for forcing major version bumps
- **Updated `prepare-release.ts`** to handle `--major` flag that bypasses automatic major→minor downgrade
- **Maintains existing behavior** for automatic releases (still downgrades major to minor)
```bash
pnpm release
pnpm release:major
```
- ✅ Storybook major version upgrades (v9 → v10)
- ✅ Nuxt major version upgrades (v3 → v4)
- ✅ Breaking API changes that should be properly versioned
- ✅ Any ecosystem alignment scenarios
- **Simple**: Just one new script, minimal code changes
- **Explicit**: Clear intent when forcing major bumps …

chore:  Add Manual Major Version Bump Capability
